// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQzolEv9X71gqvjr_D_JmP1F9dFNhC6AI',
    appId: '1:411545132055:web:43d0c8f3fd01174b041052',
    messagingSenderId: '411545132055',
    projectId: 'flash-cht-e33f1',
    authDomain: 'flash-cht-e33f1.firebaseapp.com',
    storageBucket: 'flash-cht-e33f1.appspot.com',
    measurementId: 'G-V8E2GGZ42Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEB3JoxCwdbLE_uJfyO71auDG7yhTl0Qk',
    appId: '1:411545132055:android:7fb6480ecfd9ac29041052',
    messagingSenderId: '411545132055',
    projectId: 'flash-cht-e33f1',
    storageBucket: 'flash-cht-e33f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV6EAjJfPYEuRU11blRmx3dmU7rgy0Drc',
    appId: '1:411545132055:ios:b025ca22e6eb69e0041052',
    messagingSenderId: '411545132055',
    projectId: 'flash-cht-e33f1',
    storageBucket: 'flash-cht-e33f1.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV6EAjJfPYEuRU11blRmx3dmU7rgy0Drc',
    appId: '1:411545132055:ios:f7df4e1045d9424c041052',
    messagingSenderId: '411545132055',
    projectId: 'flash-cht-e33f1',
    storageBucket: 'flash-cht-e33f1.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
